Repository google/langextract, pull requests merged in 2025-08, with the labels that each got.

#74 Add PR validation workflows and update contribution guidelines
  .github/workflows/check-linked-issue.yml
  .github/workflows/check-pr-size.yml
  CONTRIBUTING.md
Labels: size/S

#77 Fix custom comment in linked issue check
  .github/workflows/check-linked-issue.yml
Labels: size/XS

#75 Add manual trigger capability to validation workflows
  .github/workflows/check-infrastructure-changes.yml
  .github/workflows/check-linked-issue.yml
  .github/workflows/check-pr-size.yml
  .github/workflows/validate_pr_template.yaml
Labels: size/XS

#114 Add comprehensive tests for provider plugin system
  .github/workflows/ci.yaml
  langextract/providers/__init__.py
  pyproject.toml
  tests/provider_plugin_test.py
  tox.ini
Labels: size/M

#119 Adding model and config parameters to extract()
  langextract/__init__.py
  tests/extract_precedence_test.py
  tests/init_test.py
Labels: size/M, ready-to-merge

#130 Refactor schema system to support provider-specific constraints
  README.md
  examples/custom_provider_plugin/README.md
  examples/custom_provider_plugin/langextract_provider_example/provider.py
  examples/custom_provider_plugin/langextract_provider_example/schema.py
  examples/custom_provider_plugin/test_example_provider.py
  langextract/__init__.py
  langextract/factory.py
  langextract/inference.py
  langextract/providers/README.md
  langextract/providers/gemini.py
  langextract/providers/ollama.py
  langextract/providers/schemas/__init__.py
  langextract/providers/schemas/gemini.py
  langextract/resolver.py
  langextract/schema.py
  pyproject.toml
  tests/extract_precedence_test.py
  tests/extract_schema_integration_test.py
  tests/factory_schema_test.py
  tests/init_test.py
  tests/progress_test.py
  tests/provider_plugin_test.py
  tests/provider_schema_test.py
  tests/registry_test.py
  tests/schema_test.py
  tests/visualization_test.py
Labels: size/XL

#134 Release v1.0.6
  pyproject.toml
Labels: size/XS

#138 Update kwargs handling for provider models
  langextract/inference.py
  langextract/providers/gemini.py
  langextract/providers/ollama.py
  langextract/providers/openai.py
  tests/inference_test.py
  tests/test_live_api.py
Labels: size/L

#142 Add debug logging when debug=True in lx.extract()
  langextract/__init__.py
  langextract/debug_utils.py
  langextract/inference.py
  langextract/tokenizer.py
Labels: size/M

#154 Expose timeout parameter for Ollama provider
  examples/ollama/README.md
  examples/ollama/quickstart.py
  langextract/providers/ollama.py
  tests/inference_test.py
Labels: size/S

#173 Refactor imports for better module compatibility
  .pylintrc
  langextract/annotation.py
  langextract/prompting.py
  langextract/providers/gemini.py
  langextract/visualization.py
  tests/.pylintrc
  tests/annotation_test.py
  tests/extract_precedence_test.py
  tests/factory_schema_test.py
  tests/factory_test.py
  tests/inference_test.py
  tests/init_test.py
  tests/provider_plugin_test.py
  tests/provider_schema_test.py
  tests/registry_test.py
  tests/schema_test.py
  tests/test_ollama_integration.py
  tests/visualization_test.py
Labels: size/M

#176 Code maintenance updates
  .pylintrc
  langextract/__init__.py
  langextract/annotation.py
  langextract/core/debug_utils.py
  langextract/core/tokenizer.py
  langextract/extraction.py
  langextract/prompting.py
  langextract/providers/gemini.py
  langextract/visualization.py
  tests/.pylintrc
  tests/annotation_test.py
  tests/extract_precedence_test.py
  tests/factory_schema_test.py
  tests/factory_test.py
  tests/inference_test.py
  tests/init_test.py
  tests/provider_plugin_test.py
  tests/provider_schema_test.py
  tests/registry_test.py
  tests/schema_test.py
  tests/test_ollama_integration.py
  tests/visualization_test.py
Labels: size/M

#146 fix: correct the output name of the jsonl of the second medical example
  docs/examples/medication_examples.md
Labels: size/XS

#189 Fix URL detection to prevent unintended fetching
  langextract/extraction.py
  langextract/io.py
  tests/data_lib_test.py
Labels: size/S

#193 feat: Add AWS Bedrock community provider to the plugin registry
  COMMUNITY_PROVIDERS.md
Labels: size/XS

#194 fix: Allow T-prefixed TypeVars in pylint config
  .pylintrc
  langextract/data.py
  langextract/tokenizer.py
Labels: size/XS

#202 Add llama-cpp-python community provider to the plugin repository
  COMMUNITY_PROVIDERS.md
Labels: size/XS
