Repository google/langextract, pull requests merged in 2025-09, with the labels that each got.

#218 feat: Add Zenodo DOI support
  .github/scripts/zenodo_publish.py
  .github/workflows/zenodo-publish.yml
  CITATION.cff
  README.md
  pyproject.toml
Labels: size/M

#227 feat: Add show_progress parameter for independent progress bar control
  langextract/annotation.py
  langextract/extraction.py
  tests/init_test.py
Labels: size/S

#223 docs: Fix broken community support link in issue template
  .github/ISSUE_TEMPLATE/config.yml
Labels: size/XS

#248 Internal: Strengthen CI/CD security for fork PR validation
  .github/workflows/ci.yaml
Labels: size/S

#250 Add Outlines to the list of community providers
  COMMUNITY_PROVIDERS.md
Labels: size/XS
